"""Initial Migration

Revision ID: 11035ec05026
Revises: 2ecc2ec98c02
Create Date: 2020-11-01 21:00:50.559494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11035ec05026'
down_revision = '2ecc2ec98c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('title_blog', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_description'), 'blog', ['description'], unique=False)
    op.create_index(op.f('ix_blog_title_blog'), 'blog', ['title_blog'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_title_blog'), table_name='blog')
    op.drop_index(op.f('ix_blog_description'), table_name='blog')
    op.drop_table('blog')
    # ### end Alembic commands ###
